
package com.flipfit.service;

import com.flipfit.entity.Notification;
import com.flipfit.repository.NotificationRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class NotificationServiceImpl implements NotificationService {

    private final NotificationRepository notificationRepository;

    // Constructor injection
    public NotificationServiceImpl(NotificationRepository notificationRepository) {
        this.notificationRepository = notificationRepository;
    }

    @Override
    public Notification sendNotification(Notification notification) {
        // Persist the notification; ID will be generated by JPA if annotated with @GeneratedValue
        return notificationRepository.save(notification);
    }

    @Override
    @Transactional
    public Notification deleteNotification(Long notificationId) {
        // Load the entity or throw if not found
        Notification existing = notificationRepository.findById(notificationId)
                .orElseThrow(() -> new RuntimeException("Notification not found with id: " + notificationId));

        // Delete and return the deleted entity
        notificationRepository.delete(existing);
        return existing;
    }
}
